### PR TITLE
Fix saturation data for .LUMO files

### PR DESCRIPTION
**Pull request by nidadu**
Fix the output of channel saturation data depending on LUMO file version

### CODE REVIEW

**Comment by samuelpowell** [comment]
@nidadu thanks, are you able to update the README also?

**Comment by nidadu** [comment]
@samuelpowell Yes I did, thanks

**Comment by samuelpowell** [comment]
Do we not need to invert the logic on the earlier .LUMO files?

**Comment by nidadu** [comment]
It is done - see the referenced line. The name of `lf_chvalid` suggests that it indicates channels which are _valid_, hence I invert it only when writing into the saturation matrix which now highlights channels that are saturated or "not valid".

https://github.com/Gowerlabs/lumomat/blob/f639f2a4ec7cb3c581032a1fc7102d0a2cc075e5/%2Blumofile/private/load_lumo_enum.m#L312

**Comment by nidadu** [comment]
Thanks!

**Pull request merged**
