### PR TITLE
Provide option for explicit time vector in SNIRF output, fix #47

### LINKED ISSUE #47: converting issue
I tried using the fnirs on a head model to check the event marker. Later, I converted the result into a snirf file but found that I cant open the converted snirf file by Homer3.  This is the error returned by matlib: 

test5.snirf:  Invalid File Name 

Dot indexing is not supported for variables of this type. 

 

Error in MainGUI>listboxFilesErr_Callback (line 648) 

if ishandle(maingui.handles.msgbox) 

 

Error in gui_mainfcn (line 95) 

        feval(varargin{:}); 

 

Error in MainGUI (line 21) 

    gui_mainfcn(gui_State, varargin{:}); 

 

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)MainGUI('listboxFilesErr_Callback',hObject,eventdata,guidata(hObject)) 

  

Error while evaluating UIControl Callback. 

 

DataFilesClass.ErrorCheck - ERROR: In file "snirf_test3 (1).SNIRF" "data"  field is invalid.. File will not be added to data set 

DataFilesClass.ErrorCheck - ERROR: In file "test5.snirf" "data"  field is invalid.. File will not be added to data set 

Waiting for user responce, t = 30 ticks 

Do you have any idea what was going on in the data?

### PR DESCRIPTION
**Pull request by samuelpowell**
Certain analysis packages are not SNIRF compliant and do not support the compact time vector notation. This PR provides an option to write SNIRF files with an explicit time vector.

### CODE REVIEW

**Comment by samuelpowell** [comment]
@nidadu please could you test this PR as you did for #47, using the `'time', 'explicit'` option pair for the SNIRF output?

**Comment by nidadu** [comment]
@samuelpowell I've tested this. The error disappeared but I have a warning: `Warning: 'aux' field is invalid and could not be loaded in file "test3_snirf.snirf"`. This is because the time vectors in the `aux` data structure are in the compact notation.

**Comment by samuelpowell** [comment]
@nidadu okay, aux data now has an optional explicit time vector also, would you recheck?

**Comment by nidadu** [comment]
@samuelpowell The time vector for MPU data is not in the same scale as other time vectors. This is because the `node_mpu_dt` field is not in the same units as `chn_dt` (I expected both of them to be defined by `TimeUnit`).

**Comment by samuelpowell** [comment]
@nidadu good catch, I've update the data structures to load in the auxiliary data in milliseconds, such that the export is consistent. Let me know if this looks okay to you.

**Comment by nidadu** [comment]
@samuelpowell Perfect, it looks good now. I've played with Homer3 GUI and couldn't find any other issues.

**Comment by samuelpowell** [comment]
Thanks @nidadu

**Pull request merged**
