### PR TITLE
Check app data for layout

### PR DESCRIPTION
**Pull request by HBaghdadi1995**
## Background

LumoView stores all layout files in AppData/local, so if the software is running on the same computer that the tests ran on, it should be able to automatically extract the files for 'v0.1.1' & 'v0.4.0'.

### check_app_data_for_layout
Adds the `check_app_data_for_layout` function/file.

This function takes in a `group_id` and returns the **directory** and **name** of the **layout file** associated with said `group_id`.

### read_lumo

Adds a `questdlg` to ask the user if they would like to check the back end for a **layout file**.

Adds a local `lo_dir` variable so that the file can be loaded regardless of it's source.

## Testing
Tested with **layout files** v0.1.1 & v0.4.0
- **v0.1.1** succeded.
- **v0.4.0** failed due to #9

### CODE REVIEW

**Comment by samuelpowell** [comment]
Thanks @HBaghdadi1995 I'll think about this one. 

 - I am not sure that silently fixing this is sensible, because it could mean that users don't archive all the files that they need for their studies, only finding out later when they run it on a different machine.
 - I don't want any GUI items coming up, what if this is being run headless. There are some waitbars in loadlufr that should be removed for this reason.
 - It shouldn't be an error if someone is not on Windows

**Comment by HBaghdadi1995** [comment]
Thanks for your review.

With regards to the 3 issues:

1. In this case I would suggest the function would also copy over the file itself to the recording
2. That's completley fair, I wasn't sure if the `read_lumo` file changes would go through, it was done more so as a proof that this would work. I'm goign to detail 3 suggestions further down on how we could handle this.
3. This function itself should only run on computers that have the `LumoVIEW.exe` software installed, and as all installations are currently locked to windows this function would fail on mac and linux PCs regardless. As a temporary solution we could check for OS first and search other suitable environments in mac & linux. With those environments also being implemented in the `LumoVIEW.exe` code for if we would expand the software to said operating systems.

As for the suggestios I had
1. We could suggest the users call `check_app_data_for_layout` and then using the `.json` file and directory as the layout parameter when calling `read_lumo`.
2. Adding a new bool optional parameter that activates this functionality.
3. Adding a new optional parameter that points to the group_id to be loaded.

For 1 & 3, the users should be able to input the cap name, that will then be translated into an integer.

**Comment by samuelpowell** [comment]
I don't want this to be automatic, but I also don't want to be asking the users questions in something that might run as a script.

I'd like this to be implemented by splitting this into two functions:

1. The first function `find_appdata_layout` should work like your implementation, it should try and find a local layout file given an input group ID. It will return a path if it is found, and if it is not found (or it cannot be found because for example you're not running on a machine with LumoView) then you return `[]`.
2. The second function `merge_layout` takes a `.lumo` filename and a layout filename, and merges them.

Once we've validated these, they can work as follows:

1. If no layout is embedded or provided, we will run `find_appdata_layout` and if a layout is found we will inform the user as part of the warning that they can merge the `.lumo` file by calling the following function...
2. The user calls the `merge_layout` function as described.

This way we retain the simplicity you propose, do not silently change users' files, do not make requests during the execution of a script, and give a way for users to manually merge the files.

**Comment by HBaghdadi1995** [comment]
That's a good idea, I'll undo the modifications to `read_lumo` then begin modifications on `find_appdata_layout` & start creating `merge_layout` for another pull request.

**Pull request merged**
